### ISSUE TITLE
关于AABB或kd-tree加速

### ISSUE THREAD

**Issue by tigert1998** [ZJUZTJ/RayTracing#1]
似乎场景都比较小，即便写了kd-tree可能也没有很好的效果？

**Comment by Tianji95** [comment]
有加速效果的，特别是对于两个圆球，拥有大量的三角形面，如果写kd-tree的话会提升不少速度（没有写是因为当时偷懒了

**Comment by Tianji95** [comment]
> 似乎场景都比较小，即便写了kd-tree可能也没有很好的效果？
有加速效果的，特别是对于两个圆球，拥有大量的三角形面，如果写kd-tree的话会提升不少速度（没有写是因为当时偷懒了
